### ISSUE TITLE
[Refactor] Refactor DRC:  change Academic Planner's view model to be a computed property of current academic records

### ISSUE THREAD

**Issue by nilumbra** [QCampusmate-Dev-Team/QCampusmate-Mate-4-Class#3]
**Academic records**  refers to the combined records of  1) official grade records displayed on Campusmate-J's `成績照会` page and 2) plan-to-take courses added through the `履修計画` UI.

### Background
Up to this point, the `Degree Requirement Checker Tree` (卒業要件) is not reactive to adding plan-to-take courses in `Academic Planner`(履修計画). This shall be fixed in the next coming updates. Implementation-wise, defining **academic records** as a single source of truth allows leveraging `watch` and `computed` subscriber handles offered by Vue, through both DRC and AP can do further processing.

### TODOS
- [x] Define a public class field called `records_all` in DRC and a corresponding field for Chrome Storage API
- [x] Adding a course, i.e., `DRC.addCourses(courses, year, quarter)` modifies `DRC.records_all`
- [x] Delete a course, i.e.,  `DRC.deleteCourses(deleteKeys, year, quarter)` modifies `DRC.records_all` as well
- [x] Re-implement `DRC.ap` as a computed property of `records_all`, maintaining the resulting data structure as it is
- [x] Watch `records_all`, whenever it changes,
    - [ ] Recalculate the `DRCTree`
    - [x] Sync the corresponding field in Chrome Storage
