### ISSUE TITLE
[refactor][contentScript] Randomization should be done in service worker instead of content script 

### ISSUE THREAD

**Issue by nilumbra** [QCampusmate-Dev-Team/QCampusmate-Mate-4-Class#5]
### Reason
Randomization should be part of the preprocessing pipeline. Also related: #17 

### TODO
- [x] Move functions related to randomization to `@/utils/ `
- [x] Add logic that controls applying randomization to the course records before saving to Chrome Storage API or not
- [x] Restore the `randomize/成績乱数化` check box in popup
